### ISSUE TITLE
can not convert label WARN

### ISSUE THREAD

**Issue by sam0324sam** [NiNiyas/tailon#2]
Hi
I use tinylog and it use WARN label,not WARNING
![image](https://user-images.githubusercontent.com/9580348/205722381-5a89d899-ef6e-493a-afcd-18f14464f068.png)

I try to unmark WARN label in frontend
but I can't build it
```
[root@CentOS7 tailon-master]# ./build_frontend.sh
./build_frontend.sh.
> tailon@1.0.1 build
> npm install && npm upgrade && make clean && make all


up to date, audited 535 packages in 1s

42 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

up to date, audited 535 packages in 14s

42 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
rm -rf dist/3rdparty.js dist/3rdparty.css dist/main.css dist/main.js assets_vfsdata.go
node_modules/uglify-js/bin/uglifyjs --beautify -c drop_console=true ./node_modules/vue/dist/vue.min.js ./node_modules/vue-multiselect/dist/vue-multiselect.min.js ./node_modules/sockjs-client/dist/sockjs.min.js ./node_modules/html5shiv/dist/html5shiv.min.js ./node_modules/vue-loading-overlay/dist/vue-loading.min.js > dist/3rdparty.js
/bin/sh: dist/3rdparty.js: No such file or directory
make: *** [dist/3rdparty.js] Error 1
```
I don't know how to fix it.
thank you~

your tailon is the best version~

**Comment by sam0324sam** [comment]
OK,I find the answer
```
mkdir dist
```

but have other question...
```
make: *** No rule to make target `dist/materialdesignicons.css', needed by `dist/3rdparty.css'.  Stop.
```

**Comment by NiNiyas** [comment]
I  am really sorry for the late reply. I did not get any notifications.

> I use tinylog and it use WARN label,not WARNING

That's because it doesn't support WARN labels, (see here for supported labels: https://github.com/NiNiyas/tailon#labels) but I could probably add this.

> make: *** No rule to make target `dist/materialdesignicons.css', needed by `dist/3rdparty.css'.  Stop.

I tried building this using `./build_frontend.sh` and it builds just fine.

**Comment by sam0324sam** [comment]
I try to use clean system Ubuntu 22.04 in vbox but build faild ..

**Comment by sam0324sam** [comment]
Could I take a few minutes of your time to add WARN lable?
![image](https://user-images.githubusercontent.com/9580348/207264843-73d652cd-6e8d-450e-ae4e-027d1836e34a.png)
that log let me annoying .

**Comment by NiNiyas** [comment]
> I try to use clean system Ubuntu 22.04 in vbox but build faild ..

I can reproduce this. dist folder was in .gitignore because goreleaser had the same directory name. Thanks for reporting this.

> that log let me annoying .

Yes. I know that feeling.  I will add WARN label in a few minutes

**Comment by NiNiyas** [comment]
> > I try to use clean system Ubuntu 22.04 in vbox but build faild ..
> 
> I can reproduce this. dist folder was in .gitignore because goreleaser had the same directory name. Thanks for reporting this.
> 
> > that log let me annoying .
> 
> Yes. I know that feeling. I will add WARN label in a few minutes

Just pushed it. If you are on docker, you may have to wait a few minutes for the build to complete.

**Comment by sam0324sam** [comment]
thank you very much! It work find!
